title: "Matthew Casali"
email: casali.ma98@gmail.com
phone: "+1 (650)-799-5462"
description: An acoustic engineer focusing on hardware development, real-time DSP, and machine learning among other projects!
theme: minima # Or any theme you've chosen
baseurl: ""
url: "https://ma-casali.github.io"

collections:
  projects:
    output: true
    permalink: /:collection/:path/
  music:
    output: true
    permalink: /music/:path/
  other-pages:
    output: true
    permalink: /other-pages/:path/

include:
  - play-palace/build

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax-highlighter: rouge

# Social links
minima:
  social_links:
    - { platform: email, user_url: "mailto:yourname@email.com" }
    - { platform: github, user_url: "https://github.com/yourusername" }
    - { platform: linkedin, user_url: "https://linkedin.com/in/yourprofile" }